name: error

on: 
  push:
    branches:
      - main  # 你可以根据需要更改为其他分支
  pull_request:

jobs:
  empty-job:
    runs-on: ubuntu-latest

    steps:
      - name: Empty Step
        run: echo "This is an empty step.(deploy yaml)"
      - name: Push Tag
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          commit: ${{ github.sha }}
          tag: v${{ inputs.version }}
          body: Release v${{ inputs.version }}
