name: Empty Action

on: 
  push:
    branches:
      - main  # 你可以根据需要更改为其他分支
  pull_request:

jobs:
  empty-job:
    runs-on: ubuntu-latest

    steps:
      - name: Empty Step
        run: echo "This is an empty step.(dev yaml)"
